In [ ]:
import requests
import pandas as pd

url = "https://api.football-data.org/v4/competitions/"
response = requests.get(url)
# data = response.json()
data=pd.DataFrame(response.json()['competitions'])
data.head()

# df = pd.DataFrame(data['competitions'])
# df.head()

,id,area,name,code,type,emblem,plan,currentSeason,numberOfAvailableSeasons,lastUpdated
0,2176,"{'id': 2001, 'name': 'Africa', 'code': 'AFR', ...",Africa Cup,AC,CUP,https://crests.football-data.org/ac.png,TIER_FOUR,"{'id': 2385, 'startDate': '2025-12-21', 'endDa...",2,2024-01-13T11:34:43Z
1,2006,"{'id': 2001, 'name': 'Africa', 'code': 'AFR', ...",WC Qualification CAF,QCAF,CUP,None,TIER_FOUR,"{'id': 1609, 'startDate': '2023-11-15', 'endDa...",3,2022-03-13T18:51:44Z
2,2166,"{'id': 2001, 'name': 'Africa', 'code': 'AFR', ...",AFC Champions League,ACL,CUP,None,TIER_FOUR,"{'id': 1559, 'startDate': '2022-04-06', 'endDa...",1,2023-02-26T12:57:33Z
3,2023,"{'id': 2011, 'name': 'Argentina', 'code': 'ARG...",Primera B Nacional,PBN,LEAGUE,None,TIER_FOUR,"{'id': 716, 'startDate': '2021-03-13', 'endDat...",5,2023-08-01T08:40:24Z
4,2024,"{'id': 2011, 'name': 'Argentina', 'code': 'ARG...",Liga Profesional,ASL,LEAGUE,https://crests.football-data.org/LPDF.svg,TIER_TWO,"{'id': 2470, 'startDate': '2026-01-25', 'endDa...",10,2024-09-13T16:34:03Z

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        183 non-null    int64
 1   area                      183 non-null    object
 2   name                      183 non-null    object
 3   code                      122 non-null    object
 4   type                      183 non-null    object
 5   emblem                    51 non-null     object
 6   plan                      182 non-null    object
 7   currentSeason             182 non-null    object
 8   numberOfAvailableSeasons  183 non-null    int64
 9   lastUpdated               183 non-null    object
dtypes: int64(2), object(8)
memory usage: 14.4+ KB

In [14]:
df.describe()

                id  numberOfAvailableSeasons
count   183.000000                183.000000
mean   2091.846995                 13.071038
std      53.614195                 25.112940
min    2000.000000                  0.000000
25%    2045.500000                  3.000000
50%    2092.000000                  4.000000
75%    2137.500000                  9.000000
max    2186.000000                145.000000

In [15]:
df.columns

Index(['id', 'area', 'name', 'code', 'type', 'emblem', 'plan', 'currentSeason',
       'numberOfAvailableSeasons', 'lastUpdated'],
      dtype='object')

In [16]:
df.isnull().sum()

id                            0
area                          0
name                          0
code                         61
type                          0
emblem                      132
plan                          1
currentSeason                 1
numberOfAvailableSeasons      0
lastUpdated                   0
dtype: int64

In [17]:
df.corr

<bound method DataFrame.corr of        id                                               area  \
0    2176  {'id': 2001, 'name': 'Africa', 'code': 'AFR', ...
1    2166  {'id': 2001, 'name': 'Africa', 'code': 'AFR', ...
2    2006  {'id': 2001, 'name': 'Africa', 'code': 'AFR', ...
3    2023  {'id': 2011, 'name': 'Argentina', 'code': 'ARG...
4    2024  {'id': 2011, 'name': 'Argentina', 'code': 'ARG...
..    ...                                                ...
178  2178  {'id': 2267, 'name': 'World', 'code': 'INT', '...
179  2000  {'id': 2267, 'name': 'World', 'code': 'INT', '...
180  2155  {'id': 2267, 'name': 'World', 'code': 'INT', '...
181  2153  {'id': 2267, 'name': 'World', 'code': 'INT', '...
182  2167  {'id': 2267, 'name': 'World', 'code': 'INT', '...

                          name  code    type  \
0                   Africa Cup    AC     CUP
1         AFC Champions League   ACL     CUP
2         WC Qualification CAF  QCAF     CUP
3           Primera B Nacional   PBN  LEAGUE
4             Liga Profesional   ASL  LEAGUE
..                         ...   ...     ...
178        FIFA Club World Cup  FCWC     CUP
179             FIFA World Cup    WC     CUP
180  WC Qualification CONCACAF  QCCF     CUP
181            Summer Olympics   OLY     CUP
182     FIFA Women's World Cup   WCF     CUP

                                                emblem       plan  \
0              https://crests.football-data.org/ac.png  TIER_FOUR
1                                                 None  TIER_FOUR
2                                                 None  TIER_FOUR
3                                                 None  TIER_FOUR
4            https://crests.football-data.org/LPDF.svg   TIER_TWO
..                                                 ...        ...
178                                               None   TIER_TWO
179          https://crests.football-data.org/wm26.png   TIER_ONE
180                                               None  TIER_FOUR
181  https://upload.wikimedia.org/wikipedia/commons...  TIER_FOUR
182          https://crests.football-data.org/fwwc.svg   TIER_TWO

                                         currentSeason  \
0    {'id': 2385, 'startDate': '2025-12-21', 'endDa...
1    {'id': 1559, 'startDate': '2022-04-06', 'endDa...
2    {'id': 1609, 'startDate': '2023-11-15', 'endDa...
3    {'id': 716, 'startDate': '2021-03-13', 'endDat...
4    {'id': 2470, 'startDate': '2026-01-25', 'endDa...
..                                                 ...
178  {'id': 2376, 'startDate': '2025-06-15', 'endDa...
179  {'id': 2398, 'startDate': '2026-06-11', 'endDa...
180  {'id': 1651, 'startDate': '2024-03-18', 'endDa...
181  {'id': 1655, 'startDate': '2024-07-24', 'endDa...
182  {'id': 1563, 'startDate': '2023-07-20', 'endDa...

     numberOfAvailableSeasons           lastUpdated
0                           2  2024-01-13T11:34:43Z
1                           1  2023-02-26T12:57:33Z
2                           3  2022-03-13T18:51:44Z
3                           5  2023-08-01T08:40:24Z
4                          10  2024-09-13T16:34:03Z
..                        ...                   ...
178                        22  2025-05-14T13:22:23Z
179                        23  2025-12-08T05:32:32Z
180                         2  2021-11-11T10:39:10Z
181                         2  2021-07-21T15:39:38Z
182                         1  2025-05-19T12:26:30Z

[183 rows x 10 columns]>